- pkg/gcp/apis/provider_spec.go
- Removed unused SSHKeys field from API
- Added comments on API fields
Fixes #
```improvement user
Improved comments on API fields
```
/area documentation
/kind api-change
/priority critical
> Removed unused SSHKeys field and added comments on APIs

- pkg/gcp/machine_controller.go
- pkg/gcp/machine_controller_test.go
Fixes regressions from https://github.com/gardener/machine-controller-manager/pull/509/files#diff-af75cdff1c0efd51940289aeedf2ef4eR374-R379. PTAL.
Fixes #
```improvement user
NONE
```
> GetVolumeIDs now returns also CSI VolumeIDs

- Dockerfile
This fixes the rate-limiting issue while trying to pull images from the upstream repository. 
Fixes #
```improvement user
NONE
```
> Updated Docker images to GCR copy

- pkg/gcp/apis/validation/validation.go
- pkg/gcp/machine_controller_test.go
- pkg/gcp/machine_controller_util.go
Fixes #18 
```improvement user
Support creation of machines with disk type of `pd-balanced`.
```
> Enable pd-balanced disks for machines

- pkg/gcp/machine_controller.go
> Nit: Make local var lowercase

- pkg/gcp/machine_controller_util.go
- pkg/gcp/validation/validation.go
Remove the validation for the service account. If no service account is provider the VMs will be created without one.
Fixes #
```improvement user
```
> remove service account validation

- .ci/pipeline_definitions
- Dockerfile
Update golang version to 1.19.4
Fixes #
```improvement user
Updated golang version to 1.19.4
```
> Update golang version to 1.19.4

- docs/development/testing/cmek.md
Dev Manual Testing Doc for CMEK Updated
Fixes:- part of #78
```improvement developer
Enhanced Dev Testing Doc for CMEK
```
> CMEK shoot cluster manual test documentation

- Makefile
- docs/docs/provider-spec.md
- hack/api-reference/generate-spec-doc.sh
Add `make` rule for updating `provider-spec.md`
Fixes #
```improvement user
NONE
```
> Add `make` rule for updating `provider-spec.md`

- .ci/pipeline_definitions
- Dockerfile
Upgrade golang version to 1.20.5
Fixes #
```improvement user
Updated golang version to 1.20.5
```
> Upgrade golang version to 1.20.5

- docs/development/testing/cmek.md
Fixes #78
```improvement user
NONE
```
> fixed example for encryption in cmek.md

- .ci/pipeline_definitions
- Dockerfile
- go.mod
- go.sum
Update go version to `1.21.4`
Fixes #
```improvement user
NONE
```
> Update go to `1.21.4`

- .ci/local_integration_test
- .ci/pipeline_integration_test
- Makefile
This PR modifies the IT test make target to incorporate shoot as a seed setup as well as seed setup for local IT.
Fixes #
```improvement user
NONE
```
> Enhanced the local_integration_test script

- Makefile
This PR provides a flag to specify target platform for the docker image
Fixes #https://github.com/gardener/machine-controller-manager/issues/921
```improvement user
```
> Fix docker image

- docs/docs/provider-spec.md
- hack/api-reference/template/members.tpl
- hack/api-reference/template/type.tpl
This PR fixes the doc links in provider-spec.md file.
Fixes #
```improvement user
NONE
```
> Fix `gen-crd-api-referece-docs` tpl files

- pkg/gcp/validation/validation.go
Previously validation checked values of the wrong field.
```improvement user
Fix validation of Ipv6AccessType
```
> Fix validation of Ipv6AccessType

- .ci/pipeline_definitions
- Dockerfile
- go.mod
This PR updates the golang version used from `1.23.3` to `1.24.1`
Fixes #
```noteworthy developer
Golang version updated to `1.24.1`
```
> Update golang version to `1.24.1`

- .ci/check
Fixes #
cc @aaronfern 
```improvement user
```
> Update golangci-lint version

- .ci/pipeline_integration_test
Fixes #
```improvement user
```
> Fix typo in integration test script

- .gitignore
- go.mod
- pkg/gcp/machine_controller.go
- pkg/gcp/machine_controller_test.go
- pkg/gcp/machine_controller_util.go
- pkg/instrument/instrument.go
- pkg/instrument/instrument_test.go
Part of fixes for [mcm#872](https://github.com/gardener/machine-controller-manager/issues/872)
```improvement user
```
> Add driver and API request metrics
