- go.mod
- go.sum
- vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/types.go
- vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/machine_types.go
- vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/controller.go
- vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/machineclass.go
- vendor/modules.txt
- Added a more comprehensive set of events to trigger machine class reconciliations.
- Finalizers are added by default for all machine class objects.
Fixes #
```improvement operator
Added a more comprehensive set of events to trigger machine class reconciliations.
```
```improvement operator
Finalizers are added by default for all machine class objects.
```
> Bugfix: Fixed issues with machineClass finalizers

- kubernetes/secret.yaml
- pkg/gcp/apis/provider_spec.go
- pkg/gcp/apis/validation/validation.go
- pkg/gcp/fake/mockclient.go
- pkg/gcp/machine_controller_test.go
- pkg/gcp/machine_controller_util.go
- pkg/gcp/plugin.go
/area open-source usability
/kind enhancement
/priority normal
/platform gcp
All the secret keys used by Gardener are now also allowed as alternatives for this machine-controller-manager plugin. This helps to not make mappings for the data keys.
ℹ️ Similar improvement for in-tree driver: https://github.com/gardener/machine-controller-manager/pull/578/commits/0e41070979b21dae4e27fe6504bdc99f651ec3b7 (https://github.com/gardener/machine-controller-manager/pull/578)
```feature operator
The machine class secret does now also accept the data key `serviceaccount.json` as alternatives for today's key.
```
> Support Gardener credentials data keys

- kubernetes/machine-class.yaml
- pkg/gcp/machine_controller.go
- pkg/gcp/machine_controller_test.go
Validates the support for the provider in the MachineClass
Fixes [#599](https://github.com/gardener/machine-controller-manager/issues/599)
```improvement user
NONE
```
> Validate the support for the provider in the MachineClass

- .ci/pipeline_definitions
Pipeline steps will use go version 1.16.6
Fixes #
```improvement user
NONE
```
> go version in pipeline upgraded to v1.16.6

- .ci/pipeline_definitions
Test step image updated to use `test-machinery/base-step:stable` which consists of `cc/utils/cli.py` which can be used to access the kubeconfigs 
Fixes #
```improvement user
NONE
```
> Updates test step image in pipeline_definition

- .ci/component_descriptor
MCM as a dependency added in component descriptor , this will help CI pipeline job to look for version of MCM and create a PR for revendoring if needed.
Fixes #
```improvement user
NONE
```
> Component descriptor added

- .ci/pipeline_definitions
- Dockerfile
To fix latest vulnerability scan findings.
Base and build images are pulled from dockerhub.
base image `alpine:3.15.0` → `alpine:3.15.4`
build image `golang:1.17.5` → `golang:1.17.9`
Fixes #
```improvement operator
Base image updated to alpine `v3.15.4` and build image to golang `1.17.9`.
```
/invite @kon-angelo
> Update base/build images

- pkg/api/v1alpha1/provider_spec.go
- pkg/gcp/machine_controller_util.go
- pkg/gcp/validation/validation.go
Fields regarding GPU have been introduced in the providerConfig.
These expose two fields:
1. acceleratorType
2. count
`live-migration` for VM is not allowed for VM with GPU attached, so `onHostMigration=TERMINATE` needs to be configured if using MCM directly
Fixes #
a part of https://github.com/gardener/gardener-extension-provider-gcp/issues/132
```noteworthy user
VM with GPU attached can now be created on GCP. Note for a2 series machine , no need to specify `acceleratorType` and `count` as it already comes with inbuilt GPU.
```
> Adds GPU support 

- Dockerfile
- Makefile
/area security
/kind enhancement
Similar to https://github.com/gardener/machine-controller-manager-provider-openstack/pull/62
```other operator
machine-controller-manager-provider-gcp now uses `distroless` instead of `alpine` as a base image.
```
> Change base image from alpine to distroless

- pkg/gcp/validation/validation.go
Remove the validation for the service account. If no service account is provided the VMs will be created without one.
The was done with #49 but was mistakenly added again with #41.
Fixes #
```bugfix operator
A bug causing machine spec validation to fail has been fixed.
```
> Remove service account validation

- pkg/gcp/plugin.go
I spent more than an hour trying to troubleshoot `invalid character '\n' in string literal` when creating new VMs, At the end it was extra `\n` in the secret value
Thought it's better to guide the developer to the root cause of the error by enhancing the error message
Fixes #
```improvement developer
Enhance error message when decoding serviceAccountJSON fails.
```
> Better error message on ServiceAccountJSON decode failure

- .ci/pipeline_definitions
Add cve categorization for mcm-provider-gcp.
The categorization was initially defined here and it transferred as defined to the mcm-provider-gcp repository: 
https://github.com/gardener/gardener-extension-provider-gcp/pull/546 
We move the cve categorization to the mcm-provider-gcp repository as the categorization can't be taken into consideration when it is defined in the respective provider extension project. Once this behaviour has changed we can remove the categorisation here again.
```other operator
CVE categorization for mcm-provider-gcp has been added.
```
> Add cve categorization for mcm-provider-gcp

- test/integration/controller/controller_test.go
This PR increases the timeout for IT to `10min` to accommodate the time node-critical components take to get ready. https://github.com/gardener/machine-controller-manager/pull/778.
Fixes #
```improvement user
NONE
```
> Increase timeout for IT to 10 min

- .ci/pipeline_definitions
- .ci/set_dependency_version
This PR specifies the golang container image to be used by the `create-upgrade-prs` cronjob to run the `set_dependency_version` script
Fixes #
```improvement user
NONE
```
> Add image reference for `create-upgrade-prs` cronjob

- kubernetes/machine-class.yaml
- pkg/api/v1alpha1/provider_spec.go
- pkg/gcp/machine_controller_util.go
Adds support for setting the minimum CPU platform when creating VMs.
`-`
`-`
```noteworthy developer
The GCPProviderSpec now supports setting `minCpuPlatform` to configure the minimum CPU platform requested for the VM.
```
> Add support for min cpu platform

- pkg/gcp/validation/validation.go
Removes strict disk type validation. The main reason is to support https://github.com/gardener/gardener-extension-provider-gcp/issues/702. As providers add more disk types the validations need to be adapted. 
The PR could go either way, of adding the check for the new type or removing the current check and I was in favor of the later approach. 
Fixes #
```improvement user
Remove strict validation about disk types
```
> remove disk type validation

- .ci/check
- .ci/setupenv.src
- .golangci.yaml
- pkg/gcp/fake/mockserver.go
- pkg/gcp/integration/integration_test.go
- pkg/gcp/machine_controller.go
- pkg/gcp/machine_controller_util.go
- test/integration/provider/rti.go
This PR replaces the deprecated `golint` with `golangci-lint`
Fixes #
```improvement operator
golangci-lint will now be used as the linter instead of the older golint
```
> Replace goling with golangci-lint

- pkg/api/v1alpha1/provider_spec.go
- pkg/gcp/fake/mockclient.go
- pkg/gcp/machine_controller_test.go
- pkg/gcp/machine_controller_util.go
- pkg/gcp/plugin.go
- pkg/gcp/validation/validation.go
This PR enables support for credentials configuration different from a file containing service account info. This enables support for [workload identity federation](https://cloud.google.com/iam/docs/workload-identity-federation-with-kubernetes#go).
Work in progress
/hold
Part of https://github.com/gardener/gardener/issues/9586
```improvement developer
MCM can now retrieve the project ID from a "projectID" data key, allowing support for credential configurations that do not directly contain the project ID. One such case is a [workload identity credential configuration](https://cloud.google.com/iam/docs/workload-download-cred-and-grant-access).
```
> [GEP-26] Support for GCP credentials configuration

- docs/docs/provider-spec.md
- kubernetes/machine-class.yaml
- pkg/api/v1alpha1/provider_spec.go
- pkg/gcp/machine_controller_util.go
This PR adds support to provide a `shieldedInstanceConfig` for GCE VMs to be able to control the Shielded Instance Settings `vTPM`, `IntegrityMonitoring ` (both enable by default if a GCE VM is booted from an image that is `UEFI_COMPATIBLE`) and `secureBoot`(which needs to be explicitly enabled).
In order to allow be able to support secure boot enabled operaing systems on GCP, MCM provider GCP should be able to provide a `shieldedInstanceConfig` to GCP if the machineClass asks for it.
Fixes #
```improvement user
MCM provider GCP is able to provide the values for a `shieldedInstanceConfiguration` from a machineClass to the GCP API.
```
> Enable submitting shielded instance configs for VMs

- docs/docs/provider-spec.md
- kubernetes/machine-class.yaml
- pkg/api/v1alpha1/provider_spec.go
- pkg/gcp/machine_controller_util.go
- pkg/gcp/validation/validation.go
This PR will allow the GCP provider for Machine Controller Manager create Virtual Machines with IPv6 
Fixes [#829](https://github.com/gardener/gardener-extension-provider-gcp/issues/829)
```improvement user
```
> Add DualStack Support 

- Makefile
There was an issue where some make targets would fail if MCM was not present in the mod cache. This caused these targets to fail.
This PR ensures that MCM is present in the mod cache before any make targets are run.
In case it is not present in the cache, it will be downloaded along with other dependencies required by it
Fixes #
```improvement operator
Fix an issue that caused make targets to fail by ensuring MCM is present in the mod cache
```
> Ensure mcm dependency is present in mod cache before running any make targets

- docs/docs/provider-spec.md
- kubernetes/machine-class.yaml
- pkg/api/v1alpha1/provider_spec.go
- pkg/gcp/machine_controller_util.go
This PR enables extensions to pass values for the storagePool field in the provider spec.
See also https://cloud.google.com/backup-disaster-recovery/docs/concepts/storage-pools.
Fixes #
```improvement user
Add storagePool field to provider spec
```
> Enable StoragePool
